### ISSUE TITLE
RA invitation not working in some cases [5,20,0.25]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2290]
**Describe the bug**
Sometimes we invite an RA to the platform, and when they click the link they receive the platform errors out. Typically our support staff are able to click the link and see the page just fine, making this one very hard to troubleshoot.

The best guess right now comes from the following logs:
```
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.480349 #37]  INFO -- : source=rack-timeout id=ed5445af-2572-4629-85a9-60fcd1192292 wait=3ms timeout=28997ms state=ready
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.481180 #37]  INFO -- : [ed5445af-2572-4629-85a9-60fcd1192292] Started GET "/regional_ambassador/signup?admin_permission_token=[FILTERED]" for 2620:101:f000:780::1e6b at 2019-11-05 18:43:12 +0000
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.486006 #37]  INFO -- : [ed5445af-2572-4629-85a9-60fcd1192292] Processing by RegionalAmbassador::SignupsController#new as HTML
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.486125 #37]  INFO -- : [ed5445af-2572-4629-85a9-60fcd1192292]   Parameters: {"admin_permission_token"=>"[FILTERED]"}
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.511658 #37]  INFO -- : [ed5445af-2572-4629-85a9-60fcd1192292] Completed 404 Not Found in 25ms (ActiveRecord: 20.2ms)
Nov 05 10:43:12 technovation app/web.1: F, [2019-11-05T18:43:12.519573 #37] FATAL -- : [ed5445af-2572-4629-85a9-60fcd1192292]   
Nov 05 10:43:12 technovation app/web.1: F, [2019-11-05T18:43:12.519690 #37] FATAL -- : [ed5445af-2572-4629-85a9-60fcd1192292] ActiveRecord::RecordNotFound (Couldn't find SignupAttempt):
Nov 05 10:43:12 technovation app/web.1: F, [2019-11-05T18:43:12.519780 #37] FATAL -- : [ed5445af-2572-4629-85a9-60fcd1192292]   
Nov 05 10:43:12 technovation app/web.1: F, [2019-11-05T18:43:12.519879 #37] FATAL -- : [ed5445af-2572-4629-85a9-60fcd1192292] app/controllers/application_controller.rb:96:in `setup_valid_profile_from_signup_attempt'
Nov 05 10:43:12 technovation app/web.1: [ed5445af-2572-4629-85a9-60fcd1192292] app/controllers/regional_ambassador/signups_controller.rb:10:in `new'
Nov 05 10:43:12 technovation app/web.1: [ed5445af-2572-4629-85a9-60fcd1192292] lib/cloud_flare_middleware.rb:18:in `call'
Nov 05 10:43:12 technovation app/web.1: I, [2019-11-05T18:43:12.521438 #37]  INFO -- : source=rack-timeout id=ed5445af-2572-4629-85a9-60fcd1192292 wait=3ms timeout=28997ms service=41ms state=completed
Nov 05 10:43:12 technovation heroku/router: at=info method=GET path="/regional_ambassador/signup?admin_permission_token=[FILTERED]" host=my.technovationchallenge.org request_id=ed5445af-2572-4629-85a9-60fcd1192292 fwd="2620:101:f000:780::1e6b,173.245.52.67" dyno=web.1 connect=0ms service=57ms status=404 bytes=19467 protocol=https

```

That error suggests that the platform is seeing a signup token but not finding a `SignupAttempt` when we want the platform to be using the invite instead.

**To Reproduce**

**TBD**

**Expected behavior**
The invitation would work correctly for sign up.

**Comment by rsgonzal** [comment]
@ophelieh were there any issues with ChA invites last season?

**Comment by ophelieh** [comment]
Not that I can remember.
